DROP USER FSDB cascade;
DROP TABLESPACE fs_db including contents and datafiles;
DROP TABLESPACE fs_db_tmp including contents and datafiles;

-- Create the tablespace, temp tablespace and schema(user)
  CREATE TABLESPACE fs_db
  DATAFILE 'fs_db.dat' 
  SIZE 200M
  ONLINE;

  CREATE TEMPORARY TABLESPACE fs_db_tmp
  TEMPFILE 'fs_db_tmp1.dbf'
  SIZE 10M
  AUTOEXTEND ON;

  CREATE USER FSDB
  IDENTIFIED BY FootBall123
  DEFAULT TABLESPACE fs_db
  TEMPORARY TABLESPACE fs_db_tmp
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT UNLIMITED TABLESPACE TO FSDB;

-- Create Roles 
CREATE ROLE FSDB_DBA;
CREATE ROLE FSDB_STAT;
CREATE ROLE FSDB_GUEST;

-- Add users to roles
GRANT FSDB_DBA to FSDB;

-- System Privileges for role FSDB_DBA 
  GRANT CONNECT, RESOURCE, DBA TO FSDB_DBA;
  GRANT CREATE SESSION TO FSDB_DBA;
  GRANT ALL PRIVILEGES TO FSDB_DBA;
  GRANT CREATE ANY TABLE TO FSDB_DBA;
  GRANT CREATE ANY TRIGGER TO FSDB_DBA;
  GRANT CREATE ANY VIEW TO FSDB_DBA;
  GRANT CREATE PROCEDURE TO FSDB_DBA;
  GRANT CREATE SEQUENCE TO FSDB_DBA;
  GRANT CREATE SYNONYM TO FSDB_DBA;
  GRANT CREATE TABLE TO FSDB_DBA;
  GRANT CREATE TRIGGER TO FSDB_DBA;
  GRANT CREATE TYPE TO FSDB_DBA;
  GRANT CREATE VIEW TO FSDB_DBA;
  GRANT SELECT ANY TABLE TO FSDB_DBA;
