CREATE USER FDB
  IDENTIFIED BY FootBall123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
  -- 25 System Privileges for FDB 
  GRANT ALTER SYSTEM TO FDB;
  GRANT CHANGE NOTIFICATION TO FDB;
  GRANT COMMENT ANY TABLE TO FDB;
  GRANT CREATE ANY DIRECTORY TO FDB;
  GRANT CREATE ANY TABLE TO FDB;
  GRANT CREATE ANY TRIGGER TO FDB;
  GRANT CREATE ANY VIEW TO FDB;
  GRANT CREATE CLUSTER TO FDB;
  GRANT CREATE DATABASE LINK TO FDB;
  GRANT CREATE DIMENSION TO FDB;
  GRANT CREATE INDEXTYPE TO FDB;
  GRANT CREATE JOB TO FDB;
  GRANT CREATE LIBRARY TO FDB;
  GRANT CREATE MATERIALIZED VIEW TO FDB;
  GRANT CREATE OPERATOR TO FDB;
  GRANT CREATE PROCEDURE TO FDB;
  GRANT CREATE SEQUENCE TO FDB;
  GRANT CREATE SESSION TO FDB;
  GRANT CREATE SYNONYM TO FDB;
  GRANT CREATE TABLE TO FDB;
  GRANT CREATE TRIGGER TO FDB;
  GRANT CREATE TYPE TO FDB;
  GRANT CREATE VIEW TO FDB;
  GRANT SELECT ANY TABLE TO FDB;
  GRANT UNLIMITED TABLESPACE TO FDB;

  -- 1 Tablespace Quota for FDB 
  ALTER USER FDB QUOTA UNLIMITED ON USERS;

