--Create Users and Roles and assign the users to those roles

CREATE USER FSDB
  IDENTIFIED BY FootBall123
  ACCOUNT UNLOCK;

CREATE USER STAT1
  IDENTIFIED BY Stat1999
  ACCOUNT UNLOCK;

CREATE ROLE FSDB_ADMIN
  IDENTIFIED BY Admin123;

CREATE ROLE FSDB_STAT
  IDENTIFIED BY Stat123;

GRANT FSDB_ADMIN to FSDB;

GRANT FSDB_STAT to STAT1;
