--Create Users and Roles and assign the users to those roles

CREATE USER FSDB
  IDENTIFIED BY FootBall123
  ACCOUNT UNLOCK;

CREATE USER STAT1
  IDENTIFIED BY Stat1999
  ACCOUNT UNLOCK;

CREATE ROLE FSDB_ADMIN
  IDENTIFIED BY Admin123;

CREATE ROLE FSDB_STAT
  IDENTIFIED BY Stat123;

GRANT FSDB_ADMIN to FSDB;

GRANT FSDB_STAT to STAT1;

-- System Privileges for role FSDB_ADMIN 
  GRANT CONNECT, RESOURCE, DBA TO FSDB_ADMIN;
  GRANT CREATE SESSION TO FSDB_ADMIN;
  GRANT ALL PRIVILEGES TO FSDB_ADMIN;
  GRANT UNLIMITED TABLESPACE TO FSDB_ADMIN;

-- System Privileges for user FSDB
  GRANT CREATE SESSION TO FSDB;
  GRANT CREATE TABLE TO FSDB;
  GRANT UNLIMITED TABLESPACE TO FSDB;

-- System Privileges for user STAT1
  GRANT CREATE SESSION TO STAT1;
  GRANT UNLIMITED TABLESPACE TO STAT1;
