-- Log in as FSDB user in either SQL Developer or in SQL Plus by saving to a local directory and using the @ symbol
-- e.g. @create_tables.sql

--Create Tables
DROP TABLE TEAMS CASCADE CONSTRAINTS ; 

CREATE TABLE TEAMS ( 
  TEAMID NUMBER(8) NOT NULL, 
  TEAMNAME VARCHAR2 (80), 
  FAID		NUMBER (8)    NOT NULL, 
  STADIUMID	NUMBER (8),
  CONSTRAINT teams_pk PRIMARY KEY (TEAMID)
); 

DROP TABLE STADIUMS CASCADE CONSTRAINTS;

CREATE TABLE STADIUMS (
  STADIUMID	NUMBER (8) NOT NULL,
  TEAMID	NUMBER (8),
  CITY		VARCHAR2 (80),
  STADIUMNAME	VARCHAR2 (80),
  CAPACITY	NUMBER (8),
  CONSTRAINT STADIUMS_PK PRIMARY KEY (STADIUMID)
);

DROP TABLE TEAM_SEASON_STATS CASCADE CONSTRAINTS;

CREATE TABLE TEAM_SEASON_STATS (
  TESESTID	NUMBER (8) NOT NULL,
  TEAMID	NUMBER (8),
  VALUE		NUMBER (8),
  STATID	NUMBER (8),
  COMMENTS	VARCHAR2 (160),
  DATELASTUPD	DATE,
  COMPID	NUMBER (8),
  CONSTRAINT TESEST_PK PRIMARY KEY (TESESTID)
);

DROP TABLE STAT_IDS CASCADE CONSTRAINTS;

CREATE TABLE STAT_IDS (
  STATID	NUMBER (8) NOT NULL,
  DESCRIPTION	VARCHAR2 (30),
  COMMENTS	VARCHAR2 (160),
  CONSTRAINT STATID_PK PRIMARY KEY (STATID)
);

DROP TABLE COMPETITIONS CASCADE CONSTRAINTS;

CREATE TABLE COMPETITIONS (
  COMPID	NUMBER (8) NOT NULL,
  DESCRIPTION	VARCHAR2 (30),
  INDCURRENT	VARCHAR2 (1),
  STARTDATE	DATE,
  ENDDATE	DATE,
  CONSTRAINT COMPETITIONS_PK PRIMARY KEY (COMPID)
);

DROP TABLE FOOTBALL_ASSOC CASCADE CONSTRAINTS;

CREATE TABLE FOOTBALL_ASSOC (
  FAID		NUMBER (8) NOT NULL,
  COUNTRYCODE	VARCHAR2 (3),
  COUNTRY	VARCHAR2 (30),
  ASSOCNAME	VARCHAR2 (80),
  TOPDIVISION	VARCHAR2 (50),
  DOMESTICCUP	VARCHAR2 (50),
  SUPERCUP	VARCHAR2 (50),
  CONSTRAINT FAID_PK PRIMARY KEY (FAID)
);

