--------------------------------------------------------
--  File created - Sunday-December-17-2017   
--------------------------------------------------------
REM INSERTING into FSDB.FOOTBALL_ASSOC
SET DEFINE OFF;
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (1,'ALB','Albania','Federata Shqiptare e Futbollit','Kategoria Superiore','Kupa e Shqipërisë','Superkupa e Shqipërisë');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (2,'AND','Andorra','Federació Andorrana de Futbol','Primera Divisió','Copa Constitució','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (3,'ARM','Armenia','Football Federation of Armenia','Premier League','Independence Cup','SuperCup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (4,'AUT','Austria','Österreichischer Fußball-Bund','Bundesliga','ÖFB-Cup','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (5,'AZE','Azerbaijan','Az?rbaycan Futbol Federasiyalar? Assosiasiyas?','Premyer Liqas?','Azerbaijan Cup','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (6,'BLR','Belarus','Football Federation of Belarus','Vysheyshaya Liga','Belarusian Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (7,'BEL','Belgium','Koninklijke Belgische Voetbalbond','Belgian First Division A','Beker van België','Belgische Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (8,'BIH','Bosnia','Nogometni/Fudbalski Savez Bosne i Hercegovine','Premier League','Kup Bosne i Hercegovine','Super Cup (defunct)');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (9,'BUL','Bulgaria','Bulgarian Football Union','Parva Liga','Bulgarian Cup','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (10,'CRO','Croatia','Croatian Football Federation','Prva HNL','Croatian Football Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (11,'CYP','Cyprus','Cyprus Football Association','First Division','Cypriot Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (12,'CZE','Czech Republic','Fotbalová Asociace ?eské Republiky','Gambrinus Liga','Czech Cup','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (13,'DEN','Denmark','Dansk Boldspil-Union','Superligaen','Danish Cup','Supercup (defunct)');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (14,'ENG','England','The Football Association','Premier League','FA Cup','FA Community Shield');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (15,'EST','Estonia','Eesti Jalgpalli Liit','Meistriliiga','Estonian Cup','Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (16,'FRO','Faroe Islands','Fótbóltssamband Føroya','Effodeildin','Faroe Islands Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (17,'FIN','Finland','Suomen Palloliitto','Veikkausliiga','Suomen Cup','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (18,'FRA','France','Fédération Française de Football','Ligue 1','Coupe de France','Trophée des Champions');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (19,'GEO','Gerogia','Georgian Football Federation','Erovnuli Liga','Georgian Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (20,'GER','Germany','Deutscher Fußball-Bund','Bundesliga','DFB-Pokal','DFL-Supercup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (21,'GIB','Gibraltar','Gibraltar Football Association','Premier Division','Rock Cup','Pepe Reyes Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (22,'GRE','Greece','Hellenic Football Federation','Superleague','Football Cup','Super Cup (defunct)');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (23,'HUN','Hungary','Magyar Labdarúgó Szövetség','Nemzeti Bajnokság I','Magyar Kupa','Szuperkupa');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (24,'ISL','Iceland','Knattspyrnusamband Íslands','Úrvalsdeild','Icelandic Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (25,'IRL','Ireland','Football Association of Ireland','Premier Division','FAI Cup','President''s Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (26,'ISR','Israel','Israel Football Association','Premier League','State Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (27,'ITA','Italy','Federazione Italiana Giuoco Calcio','Serie A','Coppa Italia','Supercoppa Italiana');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (28,'KAZ','Kazakhstan','Football Federation of Kazakhstan','Premier League','Kazakhstan Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (29,'KVX','Kosovo','Federata e Futbollit e Kosovës','Raiffeisen Superliga','Kosovar Cup','Superkupa e Kosovës');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (30,'LVA','Latvia','Latvijas Futbola Feder?cija','Virsl?ga','Latvijas Kauss','Latvijas Superkauss');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (31,'LIE','Liechtenstein','Liechtensteiner Fußballverband','Swiss Super League','Football Cup','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (32,'LTU','Lithuania','Lietuvos Futbolo Federacija','A Lyga','LFF Taur?','LFF Supertaur?');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (33,'LUX','Luxembourg','Fédération Luxembourgeoise de Football','Division National','Coupe de Luxembourg','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (34,'MKD','Macedonia','Fudbalska Federacija na Makedonija','1. MFL','Kup na Makedonija','Super Kup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (35,'MLT','Malta','Malta Football Association','Premier League','FA Trophy','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (36,'MDA','Moldova','Federa?ia Moldoveneasc? de Fotbal','Divizia Na?ional?','Cupa Moldovei','Supercupa Moldovei');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (37,'MNE','Montenegro','Fudbalski Savez Crne Gore','1. CFL','Crnogorski Fudbalski Kup','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (38,'NED','The Netherlands','Koninklijke Nederlandse Voetbalbond','Eredivisie','KNVB Beker','Johan Cruijff Schaal');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (39,'NIR','Northern Ireland','Irish Football Association','Premiership','Irish Cup','Charity Shield');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (40,'NOR','Norway','Norges Fotballforbund','Eliteserien','Fotball Cupen','Superfinalen (defunct)');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (41,'POL','Polans','Polski Zwi?zek Pi?ki No?nej','Ekstraklasa','Puchar Polski','Superpuchar Polski');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (42,'POR','Portugal','Federação Portuguesa de Futebol','Primeira Liga','Taça de Portugal','Supertaça Cândido de Oliveira');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (43,'ROU','Romania','Federa?ia Român? de Fotbal','Liga I','Cupa României','Supercupa României');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (44,'RUS','Russia','Russian Football Union','Premier League','Russian Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (45,'SMR','San Marino','Federazione Sammarinese Giuoco Calcio','Campionato Sammarinese','Coppa Titano','Super Coppa');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (46,'SCO','Scotlans','Scottish Football Association','Premiership','Scottish Cup','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (47,'SRB','Serbia','Fudbalski Savez Srbije','SuperLiga','Kup Srbije','None');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (48,'SVK','Slovakia','Slovenský Futbalový Zväz','Super Liga','Slovenský Pohár','Slovenský Superpohár');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (49,'SVN','Slovenia','Nogometna Zveza Slovenije','1. SNL','Pokal Slovenije NZS','Superpokal Slovenije NZS');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (50,'ESP','Spain','Real Federación Española de Fútbol','La Liga','Copa del Rey','Supercopa de España');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (51,'SWE','Sweden','Svenska Fotbollförbundet','Allsvenskan','Svenska Cupen','Svenska Supercupen');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (52,'SUI','Switzerland','Association Suisse de Football','Swiss Super League','Schweizer Cup','Super Cup (defunct)');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (53,'TUR','Turkey','Türkiye Futbol Federasyonu','Süper Lig','Türkiye Kupas?','TFF Süper Kupa');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (54,'UKR','Ukraine','Football Federation of Ukraine','Premier League','Ukrainian Cup','Super Cup');
Insert into FSDB.FOOTBALL_ASSOC (FAID,COUNTRYCODE,COUNTRY,ASSOCNAME,TOPDIVISION,DOMESTICCUP,SUPERCUP) values (55,'WAL','Wales','Football Association of Wales','Premier League','Welsh Cup','None');
